spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: rootoor
    # \u8FDE\u63A5\u6C60\u914D\u7F6E
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000   # \u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u65F6\u95F4
      time-between-eviction-runs-millis: 60000  # \u914D\u7F6E\u68C0\u6D4B\u53EF\u4EE5\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\u95F4\u9694\u65F6\u95F4
      min-evictable-idle-time-millis: 300000    # \u914D\u7F6E\u8FDE\u63A5\u5728\u6C60\u4E2D\u7684\u6700\u5C0F\u751F\u5B58\u65F6\u95F4
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true  # \u6253\u5F00PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j   # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters, \u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1, 'wall'\u7528\u4E8E\u9632\u706B\u5899
      aop-patterns: com.atguigu.servie.*    # Spring\u76D1\u63A7AOP\u5207\u5165\u70B9\uFF0C\u5982x.y.z.service.*,\u914D\u7F6E\u591A\u4E2A\u82F1\u6587\u9017\u53F7\u5206\u9694
      # WebStatFilter\u914D\u7F6E
      web-stat-filter:
        enabled: true
        url-pattern: /*  # \u6DFB\u52A0\u8FC7\u6EE4\u89C4\u5219
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'   # \u5FFD\u7565\u8FC7\u6EE4\u7684\u683C\u5F0F
        session-stat-enable: true
        session-stat-max-count: 10
      # StatViewServlet\u914D\u7F6E
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*   # \u8BBF\u95EE\u8DEF\u5F84\u4E3A/druid\u65F6\uFF0C\u8DF3\u8F6C\u5230StatViewServlet
        reset-enable: false  # \u662F\u5426\u80FD\u591F\u91CD\u7F6E\u6570\u636E
        login-username: houliu   # \u9700\u8981\u8D26\u53F7\u5BC6\u7801\u624D\u80FD\u8BBF\u95EE\u63A7\u5236\u53F0
        login-password: qq123456
        allow: 127.0.0.1    # IP\u767D\u540D\u5355
        deny: 192.168.1.218   #\u3000IP\u9ED1\u540D\u5355\uFF08\u5171\u540C\u5B58\u5728\u65F6\uFF0Cdeny\u4F18\u5148\u4E8Eallow\uFF09
      # \u914D\u7F6EStatFilter
      filter:
        stat:
          log-slow-sql: true
  jackson:
    default-property-inclusion: non_null
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.houliu.pojo
  mapper-locations: classpath:mapper/*.xml